Organizations:
  - &OrdererOrg
    Name: OrderingService
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/reliance-network.com/msp

  - &Infrastructure
    Name: InfrastructureMSP
    ID: InfrastructureMSP
    MSPDir: crypto-config/peerOrganizations/infrastructure.reliance-network.com/msp
    AnchorPeers:
      - Host: peer0.infrastructure.reliance-network.com
        Port: 7051

  - &Power
    Name: PowerMSP
    ID: PowerMSP
    MSPDir: crypto-config/peerOrganizations/power.reliance-network.com/msp
    AnchorPeers:
      - Host: peer0.power.reliance-network.com
        Port: 9051

  - &Communications
    Name: CommunicationsMSP
    ID: CommunicationsMSP
    MSPDir: crypto-config/peerOrganizations/communications.reliance-network.com/msp
    AnchorPeers:
      - Host: peer0.communications.reliance-network.com
        Port: 11051

  - &Entertainment
    Name: EntertainmentMSP
    ID: EntertainmentMSP
    MSPDir: crypto-config/peerOrganizations/entertainment.reliance-network.com/msp
    AnchorPeers:
      - Host: peer0.entertainment.reliance-network.com
        Port: 13051

  - &Capital
    Name: CapitalMSP
    ID: CapitalMSP
    MSPDir: crypto-config/peerOrganizations/capital.reliance-network.com/msp
    AnchorPeers:
      - Host: peer0.capital.reliance-network.com
        Port: 15051


#Capabilities

Capabilities:
  Global: &ChannelCapabilities
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_3: true

#Application

Application: &ApplicationDefaults
  Organizations:

#Orderer
Orderer: &OrdererDefaults

  OrdererType: solo
  Addresses:
    - orderer.reliance-network.com:7050
  BatchTimeout: 5s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 256 MB
    PreferredMaxBytes: 512 KB
  Kafka:
    Brokers: 
      - 127.0.0.1:9092

  Organizations:



#Profiles
Profiles:
    OrdererGenesis:
      Capabilities:
        <<: *ChannelCapabilities
      Orderer:
        <<: *OrdererDefaults
        Organizations:
          - *OrdererOrg
        Capabilities:
          <<: *OrdererCapabilities
      Consortiums:
        SampleConsortium:
          Organizations:
            - *Infrastructure
            - *Power
            - *Communications
            - *Entertainment
            - *Capital
    ChannelThreeOrgs:
      Consortium: SampleConsortium
      Application:
        <<: *ApplicationDefaults
        Organizations:
          - *Infrastructure
          - *Power
          - *Communications
          - *Entertainment
          - *Capital
        Capabilities:
          <<: *ApplicationCapabilities
